load("test.bs").

Person := Proto clone :Person.
Person <<= :init, { | self, name | 
	System puts name.
}.

Person <<= :setName, { | self, name |
	self <- :name, name.
}.
Person <<= :getName, { | self |
	return(self -> :name).
}.

p := Person clone("isak").
p setName "isak".
p getName.
System puts(p getName()).

(1 < 10) or ((2 > 20) and (10 > 20)) or True; ifTrue {
	System puts "2 i less than 20 and 1 less than ten".
}, {
	System puts "2 i not less than 20 and 1 greater than ten".
}.